ManejoPresupuesto/Models/TipoCuenta.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ManejoPresupuesto.Models
{
    public class TipoCuenta
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo nombre es requerido, flaco")]
        [StringLength(maximumLength:50, MinimumLength = 3, ErrorMessage ="La longitud del campo {0} debe tener entre {2} y {1} caracteres")]
        [Remote(action:"VerificarExisteTipoCuenta", controller:"TipoCuenta")]
        public string Nombre { get; set; }
        public int UsuarioId { get; set; }
        public int MyProperty { get; set; }
        public int Orden { get; set; }

    }
}

ManejoPresupuesto/Controllers/CuentasController.cs
using AutoMapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Reflection;

namespace ManejoPresupuesto.Controllers
{
    public class CuentasController : Controller
    {
        private readonly IRepositorioTipoCuenta repositorioTipoCuenta;
        private readonly IServicioUsuario servicioUsuario;
        private readonly IRepositorioCuenta repositorioCuenta;
        private readonly IMapper mapper;
        private readonly IRepositorioTransaccion repositorioTransaccion;
        private readonly IServicioReportes servicioReportes;

        public CuentasController(IRepositorioTipoCuenta repositorioTipoCuenta, IServicioUsuario servicioUsuario,
            IRepositorioCuenta repositorioCuenta, IMapper mapper,
            IRepositorioTransaccion repositorioTransaccion,
            IServicioReportes servicioReportes)
        {
            this.repositorioTipoCuenta = repositorioTipoCuenta;
            this.servicioUsuario = servicioUsuario;
            this.repositorioCuenta = repositorioCuenta;
            this.mapper = mapper;
            this.repositorioTransaccion = repositorioTransaccion;
            this.servicioReportes = servicioReportes;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var cuentasConTipoCuenta = await repositorioCuenta.Buscar(usuarioId);

            var modelo = cuentasConTipoCuenta
                .GroupBy(x => x.TipoCuenta)
                .Select(grupo => new IndiceCuentasViewModel
                {
                    TipoCuenta = grupo.Key,
                    Cuentas = grupo.AsEnumerable()
                }).ToList();

            return View(modelo);


        }


        public async Task<IActionResult> Detalle(int id, int mes, int año)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var cuenta = await repositorioCuenta.ObtenerPorId(id, usuarioId);

            if (cuenta is null )
            {
                return RedirectToAction("NoEncontrado", "Home");

            }



            ViewBag.Cuenta = cuenta.Nombre;

            var modelo = await servicioReportes.ObtenerReporteTransaccionesDetalladasPorCuenta(usuarioId,id,mes,año,ViewBag); 

            return View(modelo);
        }


        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var modelo = new CuentaCreacionViewModel();
            modelo.TiposCuenta = await ObtenerTipoCuenta(usuarioId);


            return View(modelo);
        }


        [HttpPost]
        public async Task<IActionResult> Crear(CuentaCreacionViewModel cuenta)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var tipoCuenta = await repositorioTipoCuenta.ObtenerPorId(cuenta.TipoCuentaId, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            if (!ModelState.IsValid)
            {
                cuenta.TiposCuenta = await ObtenerTipoCuenta(usuarioId);
                return View(cuenta);
            }

            await repositorioCuenta.Crear(cuenta);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var cuenta = await repositorioCuenta.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");

            }

            var modelo = mapper.Map<CuentaCreacionViewModel>(cuenta);

            modelo.TiposCuenta = await ObtenerTipoCuenta(usuarioId);
            return View(modelo);
        }

        [HttpPost]

        public async Task<IActionResult> Editar(CuentaCreacionViewModel cuentaEditar)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var cuenta = await repositorioCuenta.ObtenerPorId(cuentaEditar.Id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            var tipoCuenta = await repositorioTipoCuenta.ObtenerPorId(cuentaEditar.TipoCuentaId, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioCuenta.Actualizar(cuentaEditar);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Borrar( int id)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var cuenta = await repositorioCuenta.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(cuenta);
        }


        [HttpPost]

        public async Task<IActionResult> BorrarCuenta(int id)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var cuenta = await repositorioCuenta.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioCuenta.Borrar(id);
            return RedirectToAction("Index");

        }
 
        private async Task<IEnumerable<SelectListItem>> ObtenerTipoCuenta(int usuarioId)
        {
            var tiposCuenta = await repositorioTipoCuenta.Obtener(usuarioId);
            return tiposCuenta.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }


    }
}

ManejoPresupuesto/Controllers/TipoCuentaController.cs
using Dapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace ManejoPresupuesto.Controllers
{
    public class TipoCuentaController : Controller
    {
        private readonly IRepositorioTipoCuenta repositorioTipoCuenta;
        private readonly IServicioUsuario servicioUsuario;

        public TipoCuentaController(IRepositorioTipoCuenta repositorioTipoCuenta, IServicioUsuario servicioUsuario)
        {
            this.repositorioTipoCuenta = repositorioTipoCuenta;
            this.servicioUsuario = servicioUsuario;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var tipoCuenta = await repositorioTipoCuenta.Obtener(usuarioId);
            return View(tipoCuenta);
        }
        public IActionResult Crear()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(TipoCuenta tipoCuenta) 
        {
            if (!ModelState.IsValid) 
            {
                return View(tipoCuenta);
            }

            tipoCuenta.UsuarioId = servicioUsuario.ObternerUsuarioId();

            var yaExisteTipoCuenta = await repositorioTipoCuenta.Existe(tipoCuenta.Nombre, tipoCuenta.UsuarioId);

            if (yaExisteTipoCuenta)
            {
                ModelState.AddModelError(nameof(tipoCuenta.Nombre),
                    $"El nombre {tipoCuenta.Nombre} ya existe.");
                return View(tipoCuenta);
            }


            await repositorioTipoCuenta.Crear(tipoCuenta);


            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<ActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var tipoCuenta = await repositorioTipoCuenta.ObtenerPorId(id, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta);
        }

        

        [HttpPost]
        public async Task<ActionResult> Editar(TipoCuenta tipoCuenta)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var tipoCuentaExiste = await repositorioTipoCuenta.ObtenerPorId(tipoCuenta.Id,usuarioId);

            if (tipoCuentaExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTipoCuenta.Actualizar(tipoCuenta);
            return RedirectToAction("Index");
        }

      




        [HttpGet]

        public async Task<IActionResult> VerificarExisteTipoCuenta(string nombre)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var yaExisteTipoCuenta = await repositorioTipoCuenta.Existe(nombre, usuarioId);

            if (yaExisteTipoCuenta)
            {
                return Json($"El nombre {nombre} ya existe");
            }

            return Json(true);
        }


        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var tipoCuenta = await repositorioTipoCuenta.ObtenerPorId(id, usuarioId);

            if(tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }


            return View(tipoCuenta);
        }



        [HttpPost]

        public async Task<IActionResult> BorrarTipoCuenta (int id)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var tipoCuenta = await repositorioTipoCuenta.ObtenerPorId(id, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTipoCuenta.Borrar(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Ordenar([FromBody] int[] ids)
        {
            var usuarioId = servicioUsuario.ObternerUsuarioId();
            var tipoCuenta = await repositorioTipoCuenta.Obtener(usuarioId);
            var idsTiposCuentas = tipoCuenta.Select(x => x.Id);

            var idTiposCuentasNoPertenecenAlUsuario = ids.Except(idsTiposCuentas).ToList();

            if (idTiposCuentasNoPertenecenAlUsuario.Count > 0)
            {
                return Forbid();
            }

            var tiposCuentasOrdenado = ids.Select((valor, indice) =>
                new TipoCuenta() { Id = valor, Orden = indice + 1 }).AsEnumerable();

            await repositorioTipoCuenta.Ordenar(tiposCuentasOrdenado);

            return Ok();
        }
            
       

    }
}

ManejoPresupuesto/Views/TipoCuenta/Borrar.cshtml
@model TipoCuenta

@{
    ViewData["Title"] = "Borrar Tipo de Cuenta";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card border-danger">
                <div class="card-header bg-danger text-white">
                    Confirmación de Eliminación
                </div>
                <div class="card-body text-center">
                    <h5 class="card-title mb-4">¿Está seguro que desea borrar?</h5>
                    <p class="card-text">Esta acción es irreversible y borrará toda la información relacionada con el tipo de cuenta <strong>@Model.Nombre</strong>.</p>
                    
                    <form asp-action="BorrarTipoCuenta" class="d-inline">
                        <input type="hidden" asp-for="Id" />
                        <button type="submit" class="btn btn-danger">Borrar</button>
                        <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ManejoPresupuesto/Views/TipoCuenta/Crear.cshtml
@model TipoCuenta

@{
    ViewData["Title"] = "Crear Tipo de Cuenta";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h1 class="card-title">Crear tipo de cuenta</h1>
                    <h6 class="card-subtitle mb-2 text-muted">El tipo de cuenta se refiere a cómo podemos agrupar cuentas. Ejemplos: Préstamos, tarjetas de crédito, etc.</h6>

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <form asp-action="Crear">
                        <div class="mb-3">
                            <label asp-for="Nombre" class="form-label">Nombre</label>
                            <input type="text" asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre del tipo de cuenta">
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>

                        <button type="submit" class="btn btn-primary">Enviar</button>
                        <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ManejoPresupuesto/Views/TipoCuenta/Editar.cshtml
@model TipoCuenta

@{
    ViewData["Title"] = "Editar Tipo de Cuenta";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Editar Tipo de Cuenta: @Model.Nombre
                </div>
                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <form asp-action="Editar">
                        <input type="hidden" asp-for="Id" />
                        <div class="mb-3">
                            <label asp-for="Nombre" class="form-label">Nombre</label>
                            <input type="text" asp-for="Nombre" class="form-control" placeholder="Ingresa el nuevo nombre del tipo de cuenta">
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>

                        <button type="submit" class="btn btn-primary">Guardar cambios</button>
                        <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ManejoPresupuesto/Views/TipoCuenta/Index.cshtml
@model IEnumerable<TipoCuenta>

@{
    ViewData["Title"] = "Tipos Cuentas";
}

<style>

    .custom-table {
        border-collapse: separate;
        border-spacing: 0 0.5em; /* Espacio entre filas */
        background-color: #fff; /* Fondo blanco para la tabla */
    }

        .custom-table th, .custom-table td {
            border: 1px solid #dee2e6; /* Borde sutil para las celdas */
            padding: .75rem; /* Espaciado interno */
        }

        .custom-table thead th {
            background-color: #6c757d; /* Fondo oscuro para el encabezado */
            color: #fff; /* Texto claro */
        }

    .table-hover tbody tr:hover {
        background-color: #e9ecef; /* Resaltado al pasar el mouse */
    }

    .btn-primary, .btn-danger {
        margin-right: 5px; /* Espaciado entre botones */
    }
</style>

<h1 style="color: #343a40;">Tipo de Cuentas</h1>
<h5 style="opacity: 0.8; color: #6c757d;" class="mb-4"> En esta sección usted podrá indicar la manera en que sus diferentes cuentas se pueden agrupar.</h5>

<a asp-action="Crear" class="btn btn-lg btn-outline-dark mb-2">Añadir nuevo tipo</a>

<table class="table custom-table table-hover mb-5">
    <thead class="custom-header">
        <tr>
            <th>Acciones</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody id="reordenable">
        @foreach (var tipoCuenta in Model)
        {
            <tr>
                <td>
                    <input type="hidden" value="@tipoCuenta.Id" class="ids" />
                    <a class="btn btn-sm btn-outline-primary" asp-action="Editar" asp-route-id="@tipoCuenta.Id">Editar</a>
                    <a class="btn btn-sm btn-outline-danger" asp-action="Borrar" asp-route-id="@tipoCuenta.Id">Borrar</a>
                </td>
                <td>@tipoCuenta.Nombre</td>
            </tr>
        }
    </tbody>
</table>


<a class="btn btn-outline-secondary" asp-controller="Cuentas" asp-action="Index">Volver</a>


@section Scripts {
    <script>
        const urlOrdenar = '@Url.Action("ordenar")';

        $(function(){
            $("#reordenable").sortable({
                stop: async function (e, ui) {
                   await actualizarOrdenes();
                }
            });


            async function actualizarOrdenes(){
                const ids = obtenerIdDeElementos();
               await  enviarIdABackend(ids);
            }

            function obtenerIdDeElementos() {
                const ids = $(".ids").map(function () {
                    return $(this).val();
                }).get();

                return ids;
            }


            async function enviarIdABackend(ids) {
                var data = JSON.stringify(ids);

                await fetch(urlOrdenar, {
                    method: 'POST',
                    body: data,
                    headers: {
                        'Content-Type':'application/json'
                    }
                });
            }

        })

    </script>

} 